[package]
name = "dod-benchmark"
version.workspace = true
edition.workspace = true

[[bin]]
name = "dod-benchmark"
path = "src/main.rs"

[dependencies]
analysis = { path = "../analysis" }
clap = { workspace = true, features = ["derive"] }
tabled = { workspace = true }
dem = { workspace = true }
dod = { path = "../dod" }
