// strings.js
//
// Single centralized source for every user-facing English string in the
// desktop-studio frontend. NOT an i18n system — no language switching, no
// key-based lookup abstraction beyond plain named constants/functions. The
// point is purely "one place to find/edit any UI string."
//
// Grouped by pane/feature area for readability. Static strings are plain
// values; strings built from a template/interpolation are functions that
// return the built string (keeps the interpolation logic here, not
// scattered across the pane files).
//
// Rust backend error strings (src-tauri/) and console.log/console.error
// developer diagnostics are explicitly OUT OF SCOPE and are not represented
// here — only text actually shown to the end user.

export const STRINGS = {
  // ── Top Navigation / Header ─────────────────────────────────────────────
  NAV: {
    APP_TITLE: 'DoD Tools Studio',
    CAPTURE_STUDIO_TAB: 'Capture Studio',
    RENDER_STUDIO_TAB: 'Render Studio',
    DEMO_AUDITOR_TAB: 'Demo Auditor',
    DEMO_ANALYZER_TAB: 'Demo Analyzer',
    QUICK_CLIP_LABEL: 'Quick-Clip',
    QUICK_CLIP_CAPTION: "Quick-Clip: nothing is saved to disk automatically — for grabbing a one-off clip. A re-scan replaces demos wholesale instead of preserving your edits.",
    MODE_SWITCH_TITLE: 'Toggle between Quick-Clip and Workspace mode',
    WORKSPACE_LABEL: 'Workspace',
    WORKSPACE_CAPTION: 'Workspace: saves a project file and preserves your progress across restarts and re-scans.',
    NO_SESSION_LOADED: 'No session loaded',
    SAVE_SESSION_BUTTON: 'Save Session',
    SAVE_SESSION_TITLE: 'Save Project Session',
    LOAD_SESSION_BUTTON: 'Load Session',
    LOAD_SESSION_TITLE: 'Load Project Session',
    SAVE_AS_WORKSPACE_BUTTON: 'Save as Workspace…',
    SAVE_AS_WORKSPACE_TITLE: 'Saves a project file and switches this window to Workspace mode.',
  },

  // ── Workspace Pane: Directory Scan & Master Demo Queue ──────────────────
  WORKSPACE: {
    SCAN_PANEL_TITLE: 'Directory Scan & Management',
    ADD_FILES_BUTTON: '+ Add Demo Files',
    ADD_FOLDER_BUTTON: '+ Add Folder',
    CANCEL_SCAN_BUTTON: 'Cancel Scan',
    CANCEL_SCAN_TITLE: 'Cancel the running directory scan',
    SCAN_STATUS_READY: 'Status: Ready',
    MASTER_QUEUE_TITLE: 'Master Demo Queue',
    SEARCH_PLACEHOLDER: 'Search filename or map...',
    CLEAR_UNTRACKED_BUTTON: 'Clear Untracked',
    CLEAR_UNTRACKED_TITLE: 'Remove demos with no Captured/Rendered status, notes, or edited kill range. Tracked demos are kept, in either mode. Only affects demos matching the current search.',
    CLEAR_SELECTED_BUTTON: 'Clear Selected',
    CLEAR_SELECTED_TITLE_DEFAULT: 'Check one or more rows first.',
    CLEAR_ALL_BUTTON: 'Clear All',
    CLEAR_ALL_TITLE_TOOLTIP: 'Remove every demo matching the current search — the whole queue if search is empty.',
    SELECT_ALL_CB_TITLE: 'Select/deselect all visible demos',
    TABLE_HEADER_DEMO_FILE: 'Demo File',
    TABLE_HEADER_HIGHLIGHTS: 'Highlights',
    TABLE_HEADER_PENDING: 'Pending',
    TABLE_HEADER_CAPTURED: 'Captured',
    TABLE_HEADER_RENDERED: 'Rendered',
    TABLE_HEADER_ACTIONS: 'Actions',
    TABLE_EMPTY_NO_DEMOS: "No demos scanned yet. Add a directory and click 'Scan Demos'.",
    TABLE_EMPTY_NO_DEMOS_IN_DIRS: 'No demos found in specified directories.',
    TABLE_EMPTY_NO_MATCH_SEARCH: 'No demos match your search.',
    DEMO_LIST_FOOTER_DEFAULT: 'Loaded Demos: 0 | Total Highlights: 0',
    demoListFooter: (loaded, highlights) => `Loaded Demos: ${loaded} | Total Highlights: ${highlights}`,
    REMOVE_DEMO_TITLE: 'Remove demo from queue',
    removeDemoConfirm: (name) => `Remove "${name}" from the queue? It has tracked work (Captured/Rendered status, a note, or an edited kill range) that will be lost.`,
    trackedBadgeTooltip: (reasons) => `Tracked — has ${reasons.join(', ')}. Protected from Clear Untracked in Workspace mode.`,
    rowDeleteLog: (name, trackedNote) => `[queue] Row delete: removed "${name}"${trackedNote}`,
    TRACKED_NOTE_SUFFIX: ' (had tracked work; user confirmed)',
    REASON_STATUS: 'a Captured/Rendered status',
    REASON_NOTE: 'a note',
    REASON_RANGE: 'an edited kill range',
    EMPTY_DASH: '—',
  },

  // ── Highlight Details (detail_pane.js) + Advanced Diagnostics ───────────
  HIGHLIGHTS: {
    SUBTAB_HIGHLIGHTS: 'Highlights',
    SUBTAB_CONFIGURATION: 'Configuration',
    DEFAULT_TITLE: 'Highlight Details',
    detailTitle: (name) => `Highlight Details: ${name}`,
    LAUNCH_PREVIEW_BUTTON: 'Launch Preview',
    LAUNCH_PREVIEW_TITLE: 'Patches this demo and immediately launches it in HLAE via viewdemo.',
    LAUNCHING: 'Launching…',
    VIEW_TELEMETRY_BUTTON: 'View Match Telemetry',
    SELECT_ALL_BUTTON: 'Select All',
    DESELECT_ALL_BUTTON: 'Deselect All',
    GENERATE_ALL_PREVIEWS_BUTTON: 'Generate All Previews',
    GENERATE_ALL_PREVIEWS_TITLE: 'Generates _preview.dem files with BOOKMARK events for all selected highlights across all demos.',
    GENERATING: 'Generating…',
    LAUNCH_STANDALONE_BUTTON: 'Launch Game (HLAE)',
    LAUNCH_STANDALONE_TITLE: 'Boots HLAE against hl.exe directly with no demo loaded.',
    MIN_KILLS_LABEL: 'Min Kills:',
    EMPTY_SELECT_DEMO: 'Select a demo in the Master List to view its killstreak details.',
    EMPTY_NO_STREAKS: 'No killstreak highlights detected in this demo.',
    ADVANCED_DIAGNOSTICS_SUMMARY: 'Advanced Diagnostics (Canvas Timeline & Telemetry)',
    TIMELINE_NO_DATA: 'No streak timeline available',
    COL_ROW_NUM: 'Row #',
    COL_SEL: 'Sel',
    COL_KILL_RANGE: 'Kill Range',
    COL_KILLS: 'Kills',
    COL_TIME: 'Time',
    COL_DUR: 'Dur.',
    COL_STATUS: 'Status',
    COL_NOTES: 'Notes',
    COL_DETAILS: 'Details',
    NOTES_PLACEHOLDER: 'Add note...',
    KR_RESET_TITLE: 'Reset to full range',
    fallbackKillCount: (count) => `${count} kills`,
    STATUS_OPTIONS: ['None', 'Pending', 'Captured', 'Rendered'],
    STATUS_PENDING_DEFAULT: 'Pending',
    mergedTakeBadge: (takeName) => `merged → ${takeName}`,
    mergedBadgeTitle: (mergedCount) => `Merged with ${mergedCount - 1} other highlight(s) into one take — they were recorded together and share this take folder.`,
    tickLabel: (tick) => `Tick ${tick}`,
    secondsSuffix: (n) => `${n}s`,
    HLAE_PATH_REQUIRED: 'Configure the HLAE and Half-Life executable paths in Batch Capture Config before previewing.',
    PREVIEW_LAUNCHING_TOAST: 'Preview launching in HLAE...',
    generatedPreviews: (count) => `Generated ${count} preview demo(s). Load them manually via HLAE.`,
    copiedViewCommand: (cmd) => `Copied "${cmd}" to clipboard.`,
    COPY_VIEW_COMMAND_FAILED: 'Failed to copy the view command to clipboard.',
    LAUNCHING_HLAE_TOAST: 'Launching HLAE...',
  },

  // ── Half-Life Preview Detector modal ─────────────────────────────────────
  PROCESS_DETECTOR_MODAL: {
    TITLE: 'Half-Life Preview Detector',
    BODY: 'The Half-Life engine is already running (hl.exe / hlae.exe). Launching a new preview now can corrupt the capture session — close the running instance first, or force a relaunch.',
    FORCE_RELAUNCH_BUTTON: 'Force Relaunch',
    COPY_VIEW_COMMAND_BUTTON: 'Copy View Command',
    CANCEL_BUTTON: 'Cancel',
  },

  // ── Export Configuration & Batch Capture Pipeline ────────────────────────
  CAPTURE_CONFIG: {
    PANEL_TITLE: 'Export Configuration & Batch Capture Pipeline',
    TAB_PATH_ROUTING: 'Path Routing',
    TAB_TIMING_OPTIONS: 'Timing Options',
    TAB_CAPTURE_OUTPUT: 'Capture Output',
    TAB_CUSTOM_COMMANDS: 'Custom Commands',
    HLAE_EXEC_LABEL: 'HLAE Executable:',
    HLAE_EXEC_PLACEHOLDER: 'Path to hlae.exe',
    HL_EXEC_LABEL: 'Half-Life Executable:',
    HL_EXEC_PLACEHOLDER: 'Path to hl.exe',
    FFMPEG_OVERRIDE_LABEL: 'FFmpeg Override Path:',
    FFMPEG_OVERRIDE_PLACEHOLDER: 'Optional path to ffmpeg.exe',
    BROWSE_BUTTON: 'Browse',
    WIDTH_LABEL: 'Width:',
    HEIGHT_LABEL: 'Height:',
    SEPARATE_HUD_LABEL: 'Separate HUD',
    DECAL_FLUSH_LABEL: 'Flush Decals Between Clips',
    DECAL_FLUSH_TITLE:
      'Clear bullet holes and blood off the walls between one clip and the next, so a later capture does not inherit the damage from an earlier one. Off captures the walls exactly as the engine leaves them. How many decals the engine keeps is a separate thing — set r_decals in Initial Commands.',
    SAVE_LOCAL_PATCHED_LABEL: 'Save Local Patched Copy',
    ADD_CONDEBUG_LABEL: 'Add Condebug',
    PRE_ROLL_LABEL: 'Pre-roll (s):',
    POST_ROLL_LABEL: 'Post-roll (s):',
    START_LEAD_LABEL: 'Start Lead (s):',
    STOP_TRAIL_LABEL: 'Stop Trail (s):',
    INITIAL_DELAY_LABEL: 'Initial Delay (s):',
    FF_SPEED_LABEL: 'FF Speed (x):',
    FF_SPEED_TITLE: 'Locked, matching dev — not currently user-editable.',
    CAPTURE_FPS_LABEL: 'Capture FPS:',
    OUTPUT_DIR_PLACEHOLDER: 'Capture output directory path...',
    ADD_DIRECTORY_BUTTON: 'Add Directory',
    AUTO_CLEAR_LOGS_LABEL: 'Auto-clear Logs',
    AUTO_CLEAR_PREVIEWS_LABEL: 'Auto-clear Previews',
    AUTO_CLEAR_TEMP_DEMOS_LABEL: 'Auto-clear Temp Demos',
    CLEAR_PREVIEWS_BUTTON: 'Clear Previews...',
    INIT_COMMANDS_LABEL: 'Initial Commands (executed once at demo load):',
    ADD_INIT_COMMAND_BUTTON: '+ Add Initial Command',
    // Both lists on this tab are custom commands; only one is scheduled, so
    // that is what the label says. Paired with INIT_COMMANDS_LABEL's "once at
    // demo load", the two read as the distinction they actually are.
    CUSTOM_COMMANDS_LABEL: 'Scheduled Commands (run relative to each highlight):',
    ADD_CUSTOM_COMMAND_BUTTON: '+ Add Scheduled Command',
    START_CAPTURE_BUTTON: 'Start Capture Batch',
    CANCEL_BATCH_BUTTON: 'Cancel Batch',
    STATUS_WAITING: 'Status: Waiting...',
    INIT_COMMAND_PLACEHOLDER: 'e.g. mirv_streams add all',
    CUSTOM_COMMAND_PLACEHOLDER: 'Command',
    CUSTOM_COMMAND_RELATION_OPTIONS: ['Before', 'After'],
    footerRequiredSpace: (gb) => `Required: ${gb} GB`,
    REQUIRED_SPACE_DEFAULT: 'Required: 0.00 GB',
  },

  // ── capture_pane.js runtime text (toasts, warnings, confirms) ───────────
  CAPTURE: {
    pathProblem: {
      notAbsolute: (p) => `"${p}" isn't a full path (it needs a drive letter, e.g. C:\\...)`,
      malformed: (p) => `"${p}" isn't a valid path (invalid characters or formatting)`,
      notFound: (p) => `"${p}" doesn't exist on this computer (check the spelling, or that the drive is connected)`,
      notADirectory: (p) => `"${p}" points to a file, not a folder`,
      unusable: (p) => `"${p}" is unusable`,
    },
    andNMore: (n) => `...and ${n} more`,
    NO_DRIVES_CONFIGURED_WARNING: 'No Capture Output directories configured — add at least one with free space before starting a capture.',
    noUsableSpaceProblem: (desc) => `Capture Output problem:\n${desc}`,
    NO_USABLE_SPACE_WARNING: 'None of the configured Capture Output directories have any free space.',
    insufficientSpaceWarning: (required, available) => `Insufficient disk space: capture needs ~${required} GB, only ${available} GB available across the export pool.`,
    partialProblemsWarning: (wontBeUsed, desc) => `Some Capture Output ${wontBeUsed}:\n${desc}\nCapture will proceed using the other configured directory/directories.`,
    ENTRY_WONT_BE_USED_SINGULAR: "entry won't be used",
    ENTRY_WONT_BE_USED_PLURAL: "entries won't be used",
    willBeCreatedSingle: (path, doesnt) => `${path} ${doesnt} exist yet — it'll be created when the capture starts.`,
    willBeCreatedMultiple: (doesnt, list) => `These Capture Output entries ${doesnt} exist yet — they'll be created when the capture starts:\n${list}`,
    DOESNT_SINGULAR: "doesn't",
    DOESNT_PLURAL: "don't",
    DELETE_SELECTED_DEFAULT: 'Delete Selected',
    deleteNSelected: (n) => `Delete ${n} Selected`,
    NO_ORPHANED_PREVIEWS: 'No orphaned preview demos found.',
    SCANNING_ORPHANED_PREVIEWS: 'Scanning for orphaned preview demos...',
    SCAN_COMPLETE: 'Scan complete.',
    SCAN_FAILED: 'Scan failed.',
    scanFailedRow: (e) => `Scan failed: ${e}`,
    CONFIGURE_HL_PATH_FIRST: 'Configure the Half-Life Executable (hl.exe) path before auditing previews.',
    deletePreviewsConfirm: (n) => `Permanently delete ${n} orphaned preview demo(s)?`,
    deletedPreviews: (n) => `Deleted ${n} orphaned preview demo(s).`,
    deletionFailed: (e) => `Deletion failed: ${e}`,
    CAPTURING_DEFAULT: 'Capturing',
    CAPTURING_ELLIPSIS_DEFAULT: 'Capturing...',
    capturingWithName: (status, name) => `${status}: ${name}`,
    captureErrorToast: (status) => `Capture error: ${status}`,
    CAPTURE_ERROR_STATUS_DEFAULT: 'Unknown error',
    captureErrorStatusText: (status) => `Error: ${status}`,
    CAPTURE_ERROR_TEXT_DEFAULT: 'Capture failed',
    CANCELLED: 'Cancelled',
    BATCH_CANCELLED_TOAST: 'Batch capture cancelled.',
    COMPLETED: 'Completed',
    BATCH_COMPLETED_TOAST: 'Batch capture completed successfully!',
    takesFoundMissing: (captured, total) => `${captured}/${total} takes found on disk — ${total - captured} missing.`,
    takesRenderStudioMiss: (captured, total, missingRender) => `${captured}/${total} takes captured, but ${missingRender} won't be seen by Render Studio.`,
    allTakesVerified: (total) => `All ${total} takes verified on disk.`,
    highlightsMarkedCaptured: (n) => ` ${n} highlight(s) marked Captured.`,
    BOTH_PATHS_REQUIRED: 'Please specify valid file paths for both HLAE Executable (hlae.exe) and Half-Life Executable (hl.exe).',
    NO_CAPTURE_OUTPUT_DIR: 'Configure at least one Capture Output directory before starting a capture.',
    NO_CAPTURE_OUTPUT_DIR_WITH_SPACE: 'Configure at least one Capture Output directory with free space before starting a capture.',
    insufficientDiskSpaceToast: (required, available) => `Insufficient disk space. Required: ${required} GB, Available: ${available} GB`,
    INITIALIZING_CAPTURE_BATCH: 'Initializing capture batch...',
    BATCH_QUEUED_TOAST: 'Batch capture queued successfully!',
    startBatchError: (err) => `Error starting batch: ${err}`,
    CANCELLING_BATCH_TOAST: 'Cancelling batch...',
    EMPTY_DASH: '—',
    megabytesLabel: (mb) => `${mb} MB`,
  },

  // ── Render Studio panel + render_pane.js ─────────────────────────────────
  RENDER: {
    PANEL_TITLE: 'Render Studio',
    PATH_PLACEHOLDER: 'Enter render directory path...',
    ADD_FOLDER_BUTTON: 'Add Render Folder',
    BROWSE_FOLDER_BUTTON: 'Browse Render Folder',
    CODEC_LABEL: 'Codec:',
    CODEC_PRORES: 'ProRes 422 HQ',
    CODEC_DNXHR: 'DNxHR HQ',
    CODEC_H264: 'H.264 (Software, MP4)',
    CODEC_H264_NVENC: 'H.264 (NVENC GPU, MP4)',
    SOURCE_FPS_LABEL: 'Source FPS:',
    MAX_CONCURRENT_LABEL: 'Max Concurrent Renders:',
    EXPORT_DIR_PLACEHOLDER: 'Add export drive/folder...',
    RENDER_FOLDER_ROW_PLACEHOLDER: 'Render directory path...',
    EXPORT_DIR_ROW_PLACEHOLDER: 'Export drive/folder path...',
    ADD_DRIVE_BUTTON: 'Add Drive',
    BROWSE_DRIVE_BUTTON: 'Browse Drive',
    TOTAL_EXPORT_POOL_FREE_LABEL: 'Total Export Pool Free:',
    EXPORT_POOL_FREE_DEFAULT: '0.0 GB',
    exportPoolFreeGb: (gb) => `${gb} GB`,
    SCAN_FOR_TAKES_BUTTON: 'Scan for Takes',
    TABLE_HEADER_CLIP_NAME: 'Clip Name',
    TABLE_HEADER_STREAM: 'Stream',
    TABLE_HEADER_FRAMES: 'Frames',
    TABLE_HEADER_DATE: 'Date',
    TABLE_HEADER_SETTINGS: 'Settings',
    TABLE_HEADER_SETTINGS_TITLE: "Codec/FPS this job is queued to render with — its own setting, not necessarily what the panel above currently shows",
    TABLE_HEADER_STATUS: 'Status',
    TABLE_HEADER_SPEED: 'Speed',
    TABLE_HEADER_PROGRESS: 'Progress',
    TABLE_HEADER_ACTIONS: 'Actions',
    TABLE_EMPTY: 'No render jobs queued. Scan a folder, then click Start Render Batch.',
    START_RENDER_BUTTON: 'Start Render Batch',
    CANCEL_ALL_BUTTON: 'Cancel All',
    STATUS_WAITING: 'Status: Waiting...',

    CANCEL_JOB_TITLE: 'Cancel this job',
    RESET_JOB_TITLE: 'Reset to Queued',
    VIEW_LOG_TITLE: 'View error log',
    VIEW_LOG_BUTTON: '⚠️ View Log',
    OPEN_OUTPUT_FOLDER_TITLE: "Open the rendered file's folder",
    OPEN_TAKE_FOLDER_TITLE: 'Open the source take folder',
    OPEN_OUTPUT_BUTTON: '📁 Open Output',
    OPEN_TAKE_FOLDER_BUTTON: '📁 Open Take Folder',
    QUEUE_SUMMARY_DEFAULT: '0 queued · 0 rendering · 0 done',
    queueSummary: (queued, rendering, done) => `${queued} queued · ${rendering} rendering · ${done} done`,
    ERROR_LOG_TITLE_DEFAULT: 'FFmpeg Error Log',
    errorLogTitleForJob: (name) => `FFmpeg Error Log — ${name}`,
    exportPoolFreeFooter: (gb) => `Export Pool Free: ${gb} GB`,
    RENDER_POOL_FREE_DEFAULT: 'Export Pool Free: 0.0 GB',
    recoveredJobsToast: (completed, pending) => `Recovered ${completed} completed, ${pending} pending render job(s).`,
    recoverFailed: (err) => `Failed to recover render batch: ${err}`,
    renderingStatus: (done, total) => `Status: Rendering (${done}/${total} done)`,
    BATCH_FINISHED_WITH_ERRORS: 'Render batch finished with errors — check job rows for details.',
    BATCH_CANCELLED: 'Render batch cancelled.',
    BATCH_COMPLETED: 'Render batch completed successfully!',
    STATUS_FINISHED: 'Status: Finished',
    scanFoundSoFar: (n) => `Status: Scanning… found ${n} take(s) so far`,
    ADD_RENDER_DIR_REQUIRED: 'Please add at least one render directory.',
    SCANNING_TOAST: 'Scanning render directories...',
    STATUS_SCANNING: 'Status: Scanning…',
    scannedTakesToast: (count) => `Scanned ${count} render take(s).`,
    scanCompleteStatus: (count) => `Status: Scan complete — ${count} take(s) found`,
    NO_RENDER_TAKES_DETECTED: 'No render takes detected.',
    scanDirError: (err) => `Error scanning render directories: ${err}`,
    STATUS_SCAN_FAILED: 'Status: Scan failed',
    INITIALIZING_RENDER_BATCH: 'Initializing render batch...',
    STATUS_SCANNING_FOR_TAKES: 'Status: Scanning for takes...',
    RENDER_BATCH_QUEUED: 'Render batch queued successfully!',
    renderBatchError: (err) => `Error executing render batch: ${err}`,
    CANCELLING_RENDER_BATCH: 'Cancelling render batch...',
    nvencWarning: (n) => `${n} concurrent NVENC renders may exceed your GPU's encoder session limit (often 3-5 on consumer GeForce cards). If renders start failing, lower Max Concurrent Renders.`,
    highlightsMarkedRendered: (n) => `${n} highlight(s) marked Rendered.`,
    UNKNOWN_SOURCE_FOLDER: '(unknown)',
    frameCountLabel: (n) => `${n} frames`,
  },

  // ── FFmpeg Error Log modal ───────────────────────────────────────────────
  ERROR_LOG_MODAL: {
    TITLE_DEFAULT: 'FFmpeg Error Log',
    CLOSE_BUTTON: 'Close',
  },

  // ── Render batch crash-recovery modal ────────────────────────────────────
  RENDER_RECOVERY_MODAL: {
    TITLE: '🎬 Render Batch Interrupted',
    BODY: "The last render batch didn't finish cleanly (app closed or crashed mid-batch).",
    SOURCE_LABEL: 'Source:',
    COMPLETED_LABEL: '✅ Completed:',
    PENDING_LABEL: '⏳ Pending:',
    RECOVER_BUTTON: '🔄 Recover Render Batch',
    DISCARD_BUTTON: '🗑 Discard',
  },

  // ── Demo Auditor pane + auditor_pane.js ──────────────────────────────────
  AUDITOR: {
    PANEL_TITLE: 'Demo Auditor (Deduplication)',
    TARGET_FOLDER_LABEL: 'Target Folder:',
    TARGET_FOLDER_PLACEHOLDER: 'Folder to scan for duplicate demos...',
    BROWSE_BUTTON: 'Browse',
    START_AUDIT_BUTTON: 'Start Audit',
    CANCEL_SCAN_BUTTON: 'Cancel Scan',
    STATUS_READY: 'Status: Ready to audit',
    RESULTS_TITLE: 'Duplicate Groups Found',
    DELETE_SELECTED_BUTTON: 'Delete Selected Files',
    TABLE_HEADER_STATUS: 'Status',
    TABLE_HEADER_SIZE: 'Size',
    TABLE_HEADER_FILE_PATH: 'File Path',
    TABLE_HEADER_ACTION: 'Action',
    TABLE_EMPTY: 'Choose a folder and run audit to find duplicate demo files.',
    FOOTER_DEFAULT: 'Duplicates Found: 0 | Wasted Space: 0.00 GB',
    footerSummary: (count, gb) => `Duplicates Found: ${count} | Wasted Space: ${gb} GB`,

    SELECT_FOLDER_DIALOG_TITLE: 'Select Folder to Audit',
    foundSoFarHtml: (n) => `<strong>Found ${n} demo file(s) so far&hellip;</strong>`,
    statusLineHtml: (status) => `<br><span class="text-muted">${status}</span>`,
    CHOOSE_FOLDER_FIRST: 'Choose a target folder before starting an audit.',
    INITIALIZING_HTML: '<strong>Initializing&hellip;</strong>',
    AUDITING_IN_PROGRESS_ROW: 'Auditing in progress...',
    auditFailedRow: (e) => `Audit failed: ${e}`,
    CANCELLING_HTML: '<strong>Cancelling&hellip;</strong>',
    NO_DUPLICATES_ROW: 'No duplicates found! Your demos are clean.',
    groupToggleLabel: (expanded, count) => `${expanded ? '▼' : '▶'} Group (${count} files)`,
    identicalHash: (hash) => `Identical Hash: ${hash}`,
    ORIGINAL_FILE_TITLE: 'Original file (kept)',
    FILE_ROW_LABEL: '   ↳ File',
    COPY_PATH_BUTTON: '📋 Copy Path',
    OPEN_FOLDER_BUTTON: '📁 Open Folder',
    PATH_COPIED_TOAST: 'Path copied to clipboard.',
    COPY_PATH_FAILED_TOAST: 'Failed to copy path.',
    deleteNSelectedFiles: (n) => `Delete ${n} Selected File(s)`,
    deleteConfirm: (n) => `Are you sure you want to permanently delete ${n} files?`,
    deletedFilesToast: (n) => `Successfully deleted ${n} duplicate files.`,
    deletionFailedToast: (e) => `Deletion failed: ${e}`,
    megabytesLabel: (mb) => `${mb} MB`,
  },

  // ── Clear Previews modal ─────────────────────────────────────────────────
  CLEAR_PREVIEWS_MODAL: {
    TITLE: 'Clear Previews',
    SELECT_ALL_BUTTON: 'Select All',
    SCANNING_STATUS: 'Scanning for orphaned preview demos...',
    TABLE_HEADER_FILE: 'File',
    TABLE_HEADER_SIZE: 'Size',
    TABLE_HEADER_MODIFIED: 'Modified',
    SCANNING_ROW: 'Scanning...',
    FOOTER_DEFAULT: 'Found: 0 | Reclaimable: 0.00 GB',
    foundReclaimable: (count, gb) => `Found: ${count} | Reclaimable: ${gb} GB`,
    DELETE_SELECTED_BUTTON: 'Delete Selected',
    CLOSE_BUTTON: 'Close',
  },

  // ── Demo Analyzer pane (explorer, filters, 7 report tabs) ────────────────
  ANALYZER: {
    EXPLORER_TITLE: 'Explorer',
    REFRESH_TREE_TITLE: 'Refresh folder tree',
    REFRESH_TREE_BUTTON: '⟳ Refresh',
    EXPLORER_SETTINGS_SUMMARY: '⚙ Explorer Settings',
    SHOW_FOLDER_COUNTS_LABEL: 'Show folder demo counts in the tree',
    ADD_PIN_BUTTON: '➕ Add Pin…',
    RESIZE_HANDLE_TITLE: 'Drag to resize',
    DEMOS_TITLE: 'Demos',
    SEARCH_NAME_MAP_PLACEHOLDER: 'Search name/map...',
    TYPE_ALL: 'All',
    TYPE_POV: 'POV',
    TYPE_HLTV: 'HLTV',
    MAP_PLACEHOLDER: 'Map',
    MIN_DATE_PLACEHOLDER: 'Min Date (YYYY-MM-DD)',
    MAX_DATE_PLACEHOLDER: 'Max Date (YYYY-MM-DD)',
    RESET_BUTTON: 'Reset',
    DEMO_TABLE_HEADERS: { name: 'Name', type: 'Type', map: 'Map', date: 'Date' },
    COL_TYPE: 'Type',
    COL_MAP: 'Map',
    COL_DATE: 'Date',
    ANALYZER_TITLE: 'Demo Analyzer',
    BROWSE_DEMO_BUTTON: 'Browse Demo...',
    SUBTAB_SUMMARY: 'Summary',
    SUBTAB_SCOREBOARD: 'Scoreboard',
    SUBTAB_PLAYER_DETAILS: 'Player Details',
    SUBTAB_TEAM_DETAILS: 'Team Details',
    SUBTAB_TIMELINE: 'Timeline',
    SUBTAB_ROUNDS: 'Rounds',
    SUBTAB_CHAT: 'Chat Log',
    EMPTY_PICK_DEMO: 'Pick a folder and demo on the left, browse for a file, or select one from the Workspace and click "View Match Telemetry".',
    EMPTY_PICK_DEMO_JS_FALLBACK: 'Browse for a demo file, or select one from the Workspace and click "View Match Telemetry".',

    SCANNING_WORKSPACE: 'Scanning workspace…',
    NO_DEMO_FOLDERS_FOUND: 'No demo folders found.',
    TIER_PINNED: '📌 Pinned',
    TIER_RECENT: '🕒 Recent',
    TIER_LOCAL: '📂 Local',
    PIN_FOLDER_TITLE: 'Pin folder',
    UNPIN_FOLDER_TITLE: 'Unpin folder',
    ADD_PINNED_FOLDER_DIALOG_TITLE: 'Add Pinned Folder',
    SELECT_DEMO_DIALOG_TITLE: 'Select Demo to Analyze',
    LOADING_LABEL: 'Loading…',
    THIS_PC_LABEL: '💻 This PC',
    PICK_FOLDER_FROM_SIDEBAR: 'Pick a folder from the Explorer sidebar.',
    NO_DEMOS_IN_FOLDER: 'No demos found in this folder.',
    NO_DEMOS_MATCH_FILTERS: 'No demos match the current filters.',
    ANALYZING_ELLIPSIS: 'Analyzing…',
    ANALYZING_DEMO_ELLIPSIS: 'Analyzing demo…',
    analyzingPct: (pct) => `Analyzing… ${pct}%`,
    analyzingDemoPct: (pct) => `Analyzing demo… ${pct}%`,
    analyzeFailed: (err) => `Failed to analyze demo: ${err}`,
    NO_DEMO_LOADED: 'No demo loaded',

    NO_PLAYERS_FOUND: 'No players found in this demo.',
    NO_WEAPON_DATA: 'No weapon data.',
    NO_KILL_STREAKS: 'No kill streaks recorded.',
    NO_TEAM_SCORE_EVENTS: 'No team score events recorded',
    NO_COMPLETED_ROUNDS: 'No completed rounds recorded.',
    NO_MESSAGES_MATCH_FILTERS: 'No messages match the current filters.',
    HIDE_ALL_TITLE: 'Hide all',
    SHOW_ALL_TITLE: 'Show all',
    SEARCH_SENDER_TEXT_PLACEHOLDER: 'Search sender or text...',
    CHAT_HEADING: 'Chat &amp; System Log',
    SELECT_ALL_BUTTON: 'Select All',
    CLEAR_ALL_BUTTON: 'Clear All',
    ALL_CHAT_LABEL: 'All Chat',
    TEAM_CHAT_LABEL: 'Team Chat',
    STATUS_ALL: 'All',
    STATUS_ALIVE: 'Alive',
    STATUS_DEAD: 'Dead',
    TEAM_LABEL: 'Team:',
    SYSTEM_LOGS_LABEL: 'System Logs:',
    JOINS_LEAVES_LABEL: 'Joins/Leaves',
    TEAM_CHANGES_LABEL: 'Team Changes',
    GAMEPLAY_LABEL: 'Gameplay',
    OTHER_SYSTEM_LABEL: 'Other System',

    scoreboardHeading: (alliesLabel, alliesScore, cmp, axisScore) => `Scoreboard: ${alliesLabel} (${alliesScore}) ${cmp} Axis (${axisScore})`,
    compareGlyph: (a, b) => (a > b ? '>' : (a === b ? '=' : '<')),
    durationLong: (h, m, s) => {
      if (h > 0) return `${h}h ${m}m ${s}s`;
      if (m > 0) return `${m}m ${s}s`;
      return `${s}s`;
    },
    secondsSuffix: (n) => `${n}s`,
    megabytesLabel: (mb) => `${mb} MB`,
    KD_BADGE_LABEL: 'K/D',
    partialRecordingBoth: (fmt) => `Partial recording — demo started with ${fmt} remaining and ended before the match concluded.`,
    partialRecordingStartedLate: (fmt) => `Partial recording — demo started with ${fmt} remaining on the clock.`,
    partialRecordingEndedEarly: (fmt) => `Partial recording — demo ended before the match concluded (${fmt} remaining at cutoff).`,
    groupLabelWithCount: (label, count) => `${label} — ${count} player(s)`,
    COL_NAME: 'Name',
    COL_CLASS: 'Class',
    COL_SCORE: 'Score',
    COL_KILLS: 'Kills',
    COL_DEATHS: 'Deaths',
    AXIS_LABEL: 'Axis',
    SPECTATORS_LABEL: 'Spectators',
    UNASSIGNED_LABEL: 'Unassigned',
    RECONNECTED_TITLE: 'Player reconnected mid-demo',
    PRE_DEMO_ACTIVITY_TITLE: 'Player had pre-existing stats when recording started',
    UNKNOWN_CLASS: 'Unknown',

    PLAYER_LABEL: 'Player:',
    LEGIT_PROOF_LINK_TITLE: 'Search this player on Legit-Proof',
    LEGIT_PROOF_TEXT: 'Legit-Proof',
    STEAM_PROFILE_TEXT: 'Steam Profile',
    NO_STEAM_ID: 'No Steam ID',
    STEAM_ID_LABEL: 'Steam ID: ',
    CLOCK_UNKNOWN: '??:??',
    TIMELINE_START_LABEL: '0:00',
    connectedSlot: (id) => `Connected (Slot ${id})`,
    DISCONNECTED: 'Disconnected',
    RECONNECTED_MID_DEMO: '🔄 Reconnected mid-demo',
    PRE_EXISTING_STATS: '* Pre-existing stats',
    MATCH_SCORE_TITLE: 'Match Score',
    KILLS_TITLE: 'Kills',
    DEATHS_TITLE: 'Deaths',
    AVG_LIFESPAN_TITLE: 'Avg. Lifespan',
    minMaxBadge: (min, max) => `Min: ${min}s / Max: ${max}s`,
    WEAPON_BREAKDOWN_TITLE: 'Weapon Breakdown',
    COL_WEAPON: 'Weapon',
    COL_PCT_TOTAL: '% of Total',
    COL_TEAM_KILLS: 'Team Kills',
    KILL_STREAKS_TITLE: 'Kill Streaks',
    COL_WAVE: 'Wave',
    COL_TIME: 'Time',
    COL_DURATION: 'Duration',
    WEAPON_CATEGORY_GRENADES: 'Grenades',
    WEAPON_CATEGORY_MELEE: 'Melee',
    WEAPON_CATEGORY_ALLIED: 'Allied',
    WEAPON_CATEGORY_OTHER: 'Other',

    TEAM_DETAILS_HEADING: 'Team Details',
    MATCH_OVERVIEW_TITLE: 'Match Overview',
    ROUND_SCORE_LABEL: 'Round Score',
    TOTAL_KILLS_LABEL: 'Total Kills',
    TOTAL_DEATHS_LABEL: 'Total Deaths',
    TEAM_KD_LABEL: 'Team K/D',
    ACTIVE_PLAYERS_LABEL: 'Active Players',
    TEAM_WEAPON_PERFORMANCE_TITLE: 'Team Weapon Performance',
    ALLIES_US_LABEL: 'Allies (US)',
    ALLIES_LABEL: 'Allies',
    BRITISH_LABEL: 'British',

    TEAM_SCORE_TIMELINE_TITLE: 'Team Score Timeline',

    ROUNDS_TITLE: 'Rounds',
    COL_ROUND_NUM: '#',
    COL_START_TIME: 'Start Time',
    COL_WINNER: 'Winner',
    COL_KILLS_BY_WINNER: 'Kills by Winner',

    // Summary tab
    FILE_INFO_SECTION: 'File Information',
    FILE_NAME_LABEL: 'File name',
    FILE_PATH_LABEL: 'File path',
    FILE_SIZE_LABEL: 'File size',
    FILE_CREATED_LABEL: 'File created',
    GAME_DETAILS_SECTION: 'Game Details',
    GAME_MOD_LABEL: 'Game mod',
    MAP_NAME_LABEL: 'Map name',
    MAP_CHECKSUM_LABEL: 'Map checksum',
    SERVER_INFO_SECTION: 'Server Information',
    SERVER_NAME_LABEL: 'Server name',
    SERVER_ADDRESS_LABEL: 'Server address',
    DEMO_MATCH_DETAILS_SECTION: 'Demo & Match Details',
    RECORDED_BY_LABEL: 'Recorded by',
    DEMO_TYPE_LABEL: 'Demo type',
    MATCH_TYPE_LABEL: 'Match type',
    DEMO_DURATION_LABEL: 'Demo duration',
    MATCH_DURATION_LABEL: 'Match duration',
    TECH_SPECS_SECTION: 'Technical Specifications',
    DEMO_PROTOCOL_LABEL: 'Demo protocol',
    NETWORK_PROTOCOL_LABEL: 'Network protocol',
    GAME_MOD_DOD: 'Day of Defeat',
    GAME_MOD_CS: 'Counter-Strike',
    GAME_MOD_HL: 'Half-Life',
    MATCH_TYPE_PUBLIC: 'Public / Pickup',
    MATCH_TYPE_PREGAME: 'Clan Match (Pre-game)',
    MATCH_TYPE_INCOMPLETE: 'Clan Match (Incomplete Recording)',
    MATCH_TYPE_FULL: 'Clan Match (Fully Recorded)',
    RECORDED_BY_HLTV_DEFAULT: 'HLTV',
    RECORDED_BY_UNKNOWN: 'Unknown',
    WEAPON_UNKNOWN: 'Unknown',
    EMPTY_DASH: '—',
    CHAT_DEAD_BADGE: '*DEAD*',
    CHAT_SYSTEM_TAG: '[system]',
    CHAT_TEAM_BADGE: '(Team)',
    CHAT_SENDER_UNKNOWN: 'Unknown',
  },

  // ── Clear All / Clear Selected / Remove Tracked Demo modal ───────────────
  CLEAR_ALL_MODAL: {
    TITLE_DEFAULT: 'Clear All Demos',
    SAVE_SESSION_FIRST_BUTTON: 'Save Session First',
    CLEAR_ANYWAY_DEFAULT: 'Clear Anyway',
    CANCEL_BUTTON: 'Cancel',
  },

  // ── main.js: sessions, settings dialogs, scan status, Clear actions ─────
  // Map library warnings. A demo names the map it was recorded on and stamps
  // that map's build alongside it, so "missing" and "wrong build" are different
  // problems: one cannot be played at all, the other plays and is quietly wrong.
  MAPS: {
    BANNER_TITLE: 'Maps needed',
    MISSING_LABEL: 'missing',
    WRONG_BUILD_LABEL: 'different build',
    UNREADABLE_LABEL: 'unreadable',
    DOWNLOAD_BUTTON: 'Download',
    DOWNLOAD_ALL_BUTTON: 'Download all',
    DISMISS_BUTTON: 'Dismiss',
    DOWNLOADING: 'Downloading…',
    NO_GAME_PATH: 'Set the hl.exe path in Configuration to check demo maps.',
    demoCount: (n) => (n === 1 ? '1 demo' : `${n} demos`),
    missingSummary: (maps, demos) =>
      `${maps === 1 ? '1 map' : `${maps} maps`} needed by ${demos === 1 ? '1 demo' : `${demos} demos`}`,
    wrongBuildDetail: (map, wanted, found) =>
      `${map} — these demos need build ${wanted}, the installed map is ${found}`,
    missingDetail: (map, demos) => `${map} — not installed, needed by ${demos}`,
    installedToast: (map) => `Installed ${map}`,
    alreadyCorrectToast: (map) => `${map} was already the right build`,
    replacedNote: (path) => `Previous map kept at ${path}`,
    downloadFailedToast: (map, err) => `Could not install ${map}: ${err}`,
    checkFailed: (err) => `Could not check demo maps: ${err}`,
    UNVERIFIABLE_NOTE:
      'HLTV demos do not record which map build they need, so those can only be checked for the map being present.',
  },

  // The game's own config files setting cvars this app reads. Advisory only —
  // nothing in this app writes to a config file.
  CFG: {
    BANNER_TITLE: "Your game's config files set values this app reads:",
    ADVICE:
      'These are set outside the app, so it cannot see them when it plans a capture. Either remove them from your configs, or state them in Initial Commands below so the pipeline works from the same values the engine does. Nothing here changes your config files.',
    location: (file, line) => `set in ${file}, line ${line}`,
    OVERRIDE_TITLE: 'These Initial Commands will override your config files:',
    OVERRIDE_ADVICE:
      'Init commands run after the game loads its configs, so these values win. That is usually the point — but the config line stops applying, and nothing else would tell you.',
    FROM_APP_NOTE: 'added by the app',
    SHADOWED_TITLE: 'These Initial Commands will not take effect:',
    SHADOWED_ADVICE:
      'The app appends its own commands after yours, and the last one wins. Change the setting that owns the value instead — editing the line here cannot win.',
    shadowedByApp: (cvar, yours, winner, setting) =>
      `${cvar} ${yours} never applies — the app sets ${winner} from ${setting}`,
    shadowedByYou: (cvar, yours, winner) =>
      `${cvar} ${yours} never applies — a later Initial Command sets ${winner}`,
    // Which setting owns a value the pipeline appends for itself, so the advice
    // can name the control rather than leaving the user to hunt for it.
    SETTING_FOR_CVAR: {
      mirv_movie_fps: 'Timing Options → Capture FPS',
      mirv_movie_separate_hud: 'Capture Config → Separate HUD',
      r_decals: 'Capture Config → Flush Decals Between Clips',
    },
    UNKNOWN_SETTING: 'its own setting',
    HAZARD_TITLE: 'These Scheduled Commands will break the decal flush:',
    HAZARD_ADVICE:
      'r_decals bounds how far the engine\'s decal ring may travel before it wraps — it evicts nothing. Setting it during playback strands every decal above the new limit for the rest of the demo, and the capture still completes looking plausible. Set the ring once, in Initial Commands, and leave it alone.',
    CUSTOM_TITLE: 'These Scheduled Commands override earlier values:',
    CUSTOM_ADVICE:
      'Scheduled commands run during playback, so they come after your configs and after the Initial Commands — they are the last word on whatever they set, and the only place a value changes partway through a capture.',
    hazardRow: (command) => `${command} — runs during playback`,
    customOverridesInit: (cvar, value, previous) =>
      `${cvar} ${value} replaces ${previous}, set before the demo loads`,
    customOverridesConfig: (cvar, value, previous, source) =>
      `${cvar} ${value} replaces ${previous} from ${source}`,
    override: (cvar, initValue, cfgValue, file, line) =>
      `${cvar} ${initValue} replaces ${cfgValue} from ${file}, line ${line}`,
  },

  MAIN: {
    SELECT_CAPTURE_OUTPUT_DIR_TITLE: 'Select Capture Output Directory',
    SELECT_RENDER_DIR_TITLE: 'Select Render Directory',
    SELECT_RENDER_EXPORT_DIR_TITLE: 'Select Render Export Directory',
    SAVE_PROJECT_SESSION_TITLE: 'Save Studio Project Session',
    SELECT_HLAE_EXE_TITLE: 'Select HLAE Executable (hlae.exe)',
    SELECT_HL_EXE_TITLE: 'Select Half-Life Executable (hl.exe)',
    SELECT_FFMPEG_EXE_TITLE: 'Select FFmpeg Executable (ffmpeg.exe)',
    SELECT_DEMO_FILES_TITLE: 'Select Demo Files (.dem)',
    SELECT_DEMO_FOLDER_TITLE: 'Select Demo Folder',

    JSON_PROJECT_FILTER_NAME: 'JSON Project File',
    EXECUTABLE_FILTER_NAME: 'Executable',
    DEMO_FILES_FILTER_NAME: 'Demo Files',

    NOTHING_TO_SAVE: 'Nothing to save yet — add demo files or load a session first.',
    projectSavedToast: (path) => `Project session saved successfully to ${path}`,
    SAVE_PROJECT_ERROR: 'Error saving project session.',
    loadedDemosToast: (count) => `Loaded ${count} demos from project file`,
    LOAD_PROJECT_ERROR: 'Error loading project session.',

    cancelledStatus: (count) => `Status: Cancelled — ${count} demo(s) found before cancel`,
    readyFoundStatus: (count) => `Status: Ready — ${count} demo(s) found`,
    statusGeneric: (status) => `Status: ${status}`,
    SCAN_CANCEL_REQUESTED_TOAST: 'Scan cancellation requested.',
    SCANNING_STATUS: 'Status: Scanning...',
    SCANNING_TOAST: 'Scanning directories...',
    SCANNING_PLEASE_WAIT_ROW: 'Scanning... please wait.',
    scanCompleteToast: (count) => `Scan complete (${count} demo(s) found)`,
    scanErrorToast: (err) => `Error: ${err}`,
    scanErrorStatus: (err) => `Status: Error — ${err}`,

    EXPORT_POOL_FREE_DEFAULT: 'Capture Output Free: 0.0 GB',
    exportPoolFree: (gb) => `Capture Output Free: ${gb} GB`,
    EXPORT_POOL_ERROR: 'Capture Output Free: Error calculating space',

    QUEUE_ALREADY_EMPTY: 'Queue is already empty.',
    NO_DEMOS_MATCH_SEARCH: 'No demos match the current search.',
    filterScopeNote: (visible, total) => ` (search filter active — only considered ${visible} of ${total} demo(s) in the queue)`,
    NOTHING_TRACKED_TO_CLEAR: 'Nothing to clear — every visible demo has tracked work on it.',
    removedUntrackedToast: (count, keptNote, scopeNote) => `Removed ${count} untracked demo(s)${keptNote}.${scopeNote}`,
    keptWithTrackedWork: (count) => `, kept ${count} with tracked work`,
    clearUntrackedLog: (count, keptNote, scopeNote, names) => `[queue] Clear Untracked: removed ${count} demo(s)${keptNote}.${scopeNote} — ${names}`,

    CLEAR_SELECTED_TITLE: 'Clear Selected Demos',
    CLEAR_ALL_TITLE: 'Clear All Demos',
    REMOVE_TRACKED_DEMO_TITLE: 'Remove Tracked Demo',
    CLEAR_SELECTED_ANYWAY: 'Clear Selected Anyway',
    CLEAR_ALL_ANYWAY: 'Clear All Anyway',
    REMOVE_ANYWAY: 'Remove Anyway',
    CLEAR_ANYWAY_DEFAULT: 'Clear Anyway',
    DEMO_SINGULAR: 'demo',
    DEMO_PLURAL: 'demos',
    VERB_REMOVES: 'removes',
    clearSummaryTracked: (verb, count, plural, trackedCount) => `This ${verb} ${count} ${plural} — ${trackedCount} of them have tracked work (Captured/Rendered status, a note, or an edited kill range) that will be lost. This cannot be undone.`,
    clearSummaryUntracked: (verb, count, plural) => `This ${verb} ${count} ${plural}. None currently have tracked work on them. This cannot be undone.`,

    NO_DEMOS_SELECTED: 'No demos selected — check rows in the queue first.',
    allSelectedHiddenToast: (count) => `All ${count} selected demo(s) are hidden by the current search — nothing visible to remove.`,
    hiddenCheckedNote: (count) => ` (${count} other selected demo(s) hidden by the search filter were left untouched)`,
    removeSelectedConfirm: (count, hiddenNote) => `Remove ${count} selected demo(s) from the queue?${hiddenNote}`,
    removedSelectedToast: (savedFirst, count, hiddenNote) => `${savedFirst ? 'Saved, then removed' : 'Removed'} ${count} demo(s) from the queue.${hiddenNote}`,
    clearSelectedLog: (count, savedNote, hiddenNote, names) => `[queue] Clear Selected: removed ${count} demo(s)${savedNote}.${hiddenNote} — ${names}`,
    removeAllConfirm: (count, note) => `Remove ${count} demo(s) from the queue? None have tracked work on them.${note}`,
    clearedAllToast: (savedFirst, count, note) => `${savedFirst ? 'Saved, then cleared' : 'Cleared'} ${count} demo(s) from the queue.${note}`,
    clearAllLog: (count, savedNote, note, names) => `[queue] Clear All: removed ${count} demo(s)${savedNote}.${note} — ${names}`,
    SAVED_SESSION_FIRST_NOTE: ' (saved session first)',
  },

  // ── list_editor.js: shared row-list widget (Browse/Move/Remove) ─────────
  LIST_EDITOR: {
    BROWSE_TITLE: 'Browse…',
    MOVE_UP_TITLE: 'Move up',
    MOVE_DOWN_TITLE: 'Move down',
    REMOVE_TITLE: 'Remove',
    REMOVE_ARIA_LABEL: 'Remove',
  },

  // ── ipc_bridge.js: error-toast prefixes wrapping backend errors ─────────
  IPC: {
    scanError: (err) => `Scan error: ${err}`,
    validationError: (err) => `Validation error: ${err}`,
    analysisError: (err) => `Analysis error: ${err}`,
    previewFailed: (err) => `Preview failed: ${err}`,
    processCheckFailed: (err) => `Process check failed: ${err}`,
    launchFailed: (err) => `Launch failed: ${err}`,
    killEngineFailed: (err) => `Failed to close running engine processes: ${err}`,
    batchPreviewFailed: (err) => `Batch preview generation failed: ${err}`,
    simulationError: (err) => `Simulation error: ${err}`,
    cancelScanError: (err) => `Cancel scan error: ${err}`,
    settingsLoadFailed: (err) => `Failed to load settings: ${err}`,
    settingsSaveFailed: (err) => `Failed to save settings: ${err}`,
    auditFailed: (err) => `Audit failed: ${err}`,
    deletionFailed: (err) => `Deletion failed: ${err}`,
    cancelAuditError: (err) => `Cancel audit error: ${err}`,
    folderOpenFailed: (err) => `Could not open folder: ${err}`,
    previewScanFailed: (err) => `Preview scan failed: ${err}`,
    previewDeletionFailed: (err) => `Preview deletion failed: ${err}`,
    logFileOpenFailed: (err) => `Could not open the log file: ${err}`,
  },

  // ── error_reporter.js: the one user-facing crash toast ───────────────────
  ERROR_REPORTER: {
    somethingWentWrong: (message) => `Something went wrong (${message}). Details logged to crash_log.md.`,
  },

  // ── Footer ────────────────────────────────────────────────────────────
  FOOTER: {
    VIEW_LOGS_BUTTON: 'View Logs',
    VIEW_LOGS_TITLE: "Open today's activity log in Explorer",
  },
};
