//! Diagnostics and benchmarking tool to scan user demo folders,
//! deduplicate demos, verify correctness, and measure speedups.

use analysis::Analysis;
use clap::Parser;
use std::collections::HashMap;
use std::collections::hash_map::DefaultHasher;
use std::fs;
use std::hash::{Hash, Hasher};
use std::io::Read;
use std::path::{Path, PathBuf};
use std::time::Duration;
use tabled::{builder::Builder, settings::Style};

#[derive(Parser, Debug)]
#[command(version)]
struct Args {
    /// Folder paths to scan for .dem files
    paths: Vec<PathBuf>,

    /// Limit the number of parsed demos for benchmark (default 50 to complete fast, pass 99999 for all)
    #[arg(long, default_value_t = 50)]
    limit: usize,
}

#[derive(Eq, PartialEq, Hash, Debug, Clone)]
struct FileKey {
    size: u64,
    header_hash: u64,
}

struct DemoResult {
    path: PathBuf,
    map_name: String,
    size_mb: f64,
    total_frames: usize,
    live_frame: Option<usize>,
    skipped_pct: f64,
    unopt_time: Duration,
    opt_time: Duration,
    speedup: f64,
    mismatch: Option<String>,
}

fn main() {
    let args = Args::parse();
    if args.paths.is_empty() {
        eprintln!("Usage: dod-tools-benchmark <folder1> <folder2> ...");
        std::process::exit(1);
    }

    println!("Scanning directories...");
    let mut files = vec![];
    for folder in &args.paths {
        if folder.exists() {
            scan_dir(folder, &mut files);
        } else {
            eprintln!("Warning: Path does not exist: {}", folder.display());
        }
    }

    println!("Found {} total .dem files. Deduplicating...", files.len());
    
    // Group files by FileKey to identify duplicates
    let mut groups: HashMap<FileKey, Vec<PathBuf>> = HashMap::new();
    for path in files {
        if let Ok(key) = get_file_key(&path) {
            groups.entry(key).or_default().push(path);
        } else {
            // Unreadable files get a unique key based on path
            let mut hasher = DefaultHasher::new();
            path.hash(&mut hasher);
            let dummy_key = FileKey { size: 0, header_hash: hasher.finish() };
            groups.entry(dummy_key).or_default().push(path);
        }
    }

    // Sort paths alphabetically within each group so original vs duplicate selection is stable
    for paths in groups.values_mut() {
        paths.sort();
    }

    let mut unique_files = vec![];
    let mut duplicate_groups = vec![];
    let mut duplicate_count = 0;
    let mut space_wasted_bytes: u64 = 0;

    for (key, paths) in &groups {
        if !paths.is_empty() {
            unique_files.push(paths[0].clone());
            if paths.len() > 1 {
                duplicate_groups.push((key.clone(), paths.clone()));
                duplicate_count += paths.len() - 1;
                space_wasted_bytes += key.size * (paths.len() - 1) as u64;
            }
        }
    }

    // Sort unique files alphabetically so traversal is deterministic
    unique_files.sort();

    // Sort duplicate groups by wasted space descending
    duplicate_groups.sort_by(|a, b| {
        let space_a = a.0.size * (a.1.len() - 1) as u64;
        let space_b = b.0.size * (b.1.len() - 1) as u64;
        space_b.cmp(&space_a)
    });

    println!(
        "Deduplication complete: {} unique files, {} duplicates skipped. Wasted space: {:.2} GB",
        unique_files.len(),
        duplicate_count,
        space_wasted_bytes as f64 / (1024.0 * 1024.0 * 1024.0)
    );

    // Generate duplicate report markdown
    let mut report_content = String::new();
    report_content.push_str("# Demo Deduplication Report\n\n");
    report_content.push_str("Generated by the `dod-tools-benchmark` tool.\n\n");
    report_content.push_str("## Summary\n\n");
    report_content.push_str(&format!("* **Total Files Scanned**: {}\n", groups.values().map(|v| v.len()).sum::<usize>()));
    report_content.push_str(&format!("* **Unique Demos**: {}\n", unique_files.len()));
    report_content.push_str(&format!("* **Duplicate Files Skipped**: {}\n", duplicate_count));
    report_content.push_str(&format!("* **Wasted Space**: {:.2} MB ({:.2} GB)\n\n", 
        space_wasted_bytes as f64 / (1024.0 * 1024.0),
        space_wasted_bytes as f64 / (1024.0 * 1024.0 * 1024.0)
    ));
    
    report_content.push_str("## Duplicate Groups Found\n");
    report_content.push_str("All files under each group have identical content (same byte size and header hash). You can safely delete the duplicate files listed under \"Duplicates\".\n\n");

    for (i, (key, paths)) in duplicate_groups.iter().enumerate() {
        let size_mb = key.size as f64 / (1024.0 * 1024.0);
        let total_wasted_mb = size_mb * (paths.len() - 1) as f64;
        report_content.push_str(&format!("### Group {} (Size: {:.2} MB, Wasted: {:.2} MB, Hash: {:x})\n", 
            i + 1, size_mb, total_wasted_mb, key.header_hash));
        
        report_content.push_str(&format!("* **Original File**: `{}`\n", paths[0].display()));
        report_content.push_str("* **Duplicates**:\n");
        for dup in &paths[1..] {
            report_content.push_str(&format!("  - `{}`\n", dup.display()));
        }
        report_content.push_str("\n");
    }

    if let Err(e) = fs::write("demo_deduplication_report.md", &report_content) {
        eprintln!("Error writing duplicates report: {}", e);
    } else {
        println!("Detailed deduplication report written to: demo_deduplication_report.md");
    }

    let limit = args.limit;
    if unique_files.len() > limit {
        println!("Limiting benchmark evaluation to the first {} unique files (use --limit <num> to customize).", limit);
        unique_files.truncate(limit);
    }

    let mut results = vec![];
    let total_unique = unique_files.len();

    for (i, path) in unique_files.into_iter().enumerate() {
        println!("[{}/{}] Parsing: {}", i + 1, total_unique, path.display());
        match benchmark_demo(&path) {
            Ok(res) => {
                if let Some(ref err) = res.mismatch {
                    eprintln!("  [MISMATCH] Correctness check failed: {}", err);
                } else {
                    println!(
                        "  -> Map: {}, Size: {:.2} MB, Frames: {}, Skipped: {} ({:.1}%), Speedup: {:.2}x",
                        res.map_name,
                        res.size_mb,
                        res.total_frames,
                        res.live_frame.map_or("None".to_string(), |idx| idx.to_string()),
                        res.skipped_pct,
                        res.speedup
                    );
                }
                results.push(res);
            }
            Err(e) => {
                eprintln!("  [ERROR] Failed to parse: {}", e);
            }
        }
    }

    print_report(&results);
}

fn scan_dir(dir: &Path, files: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                scan_dir(&path, files);
            } else if path.extension().map_or(false, |ext| ext.eq_ignore_ascii_case("dem")) {
                files.push(path);
            }
        }
    }
}

fn get_file_key(path: &Path) -> Result<FileKey, std::io::Error> {
    let metadata = fs::metadata(path)?;
    let size = metadata.len();
    
    // Hash the first 64KB (or less if the file is smaller)
    let mut file = fs::File::open(path)?;
    let read_size = std::cmp::min(size, 65536) as usize;
    let mut buffer = vec![0; read_size];
    file.read_exact(&mut buffer)?;
    
    let mut hasher = DefaultHasher::new();
    buffer.hash(&mut hasher);
    let header_hash = hasher.finish();
    
    Ok(FileKey { size, header_hash })
}

fn benchmark_demo(path: &Path) -> Result<DemoResult, String> {
    let file_bytes = fs::read(path).map_err(|e| format!("Read error: {}", e))?;
    let size_mb = file_bytes.len() as f64 / (1024.0 * 1024.0);

    let (analysis, diag) = Analysis::parse_with_diagnostics(&file_bytes)?;
    
    let skipped_pct = if let Some(live_frame) = diag.live_frame_index {
        (live_frame as f64 / diag.total_frames as f64) * 100.0
    } else {
        0.0
    };

    let speedup = diag.unopt_duration.as_secs_f64() / diag.opt_duration.as_secs_f64();

    Ok(DemoResult {
        path: path.to_path_buf(),
        map_name: analysis.demo_info.map_name,
        size_mb,
        total_frames: diag.total_frames,
        live_frame: diag.live_frame_index,
        skipped_pct,
        unopt_time: diag.unopt_duration,
        opt_time: diag.opt_duration,
        speedup,
        mismatch: if diag.states_matched { None } else { diag.mismatch_reason },
    })
}

fn print_report(results: &[DemoResult]) {
    if results.is_empty() {
        println!("No successful runs to report.");
        return;
    }

    let mut table_builder = Builder::default();
    table_builder.push_record([
        "File",
        "Map",
        "Size (MB)",
        "Frames",
        "Live Frame",
        "Skip %",
        "Unopt (ms)",
        "Opt (ms)",
        "Speedup",
        "Correct?",
    ]);

    let mut total_unopt = Duration::ZERO;
    let mut total_opt = Duration::ZERO;
    let mut total_size = 0.0;
    let mut total_frames = 0;
    let mut mismatch_count = 0;

    for res in results {
        let file_name = res.path.file_name().and_then(|n| n.to_str()).unwrap_or("unknown");
        let live_frame_str = res.live_frame.map_or("None".to_string(), |idx| idx.to_string());
        
        table_builder.push_record([
            file_name.to_string(),
            res.map_name.clone(),
            format!("{:.1}", res.size_mb),
            res.total_frames.to_string(),
            live_frame_str,
            format!("{:.1}%", res.skipped_pct),
            format!("{:.1}", res.unopt_time.as_secs_f64() * 1000.0),
            format!("{:.1}", res.opt_time.as_secs_f64() * 1000.0),
            format!("{:.2}x", res.speedup),
            match &res.mismatch {
                None => "YES".to_string(),
                Some(err) => {
                    mismatch_count += 1;
                    format!("NO: {}", err)
                }
            },
        ]);

        total_unopt += res.unopt_time;
        total_opt += res.opt_time;
        total_size += res.size_mb;
        total_frames += res.total_frames;
    }

    let mut table = table_builder.build();
    table.with(Style::markdown());

    println!("\n### Parsing Benchmarks & Correctness Report\n");
    println!("{}", table);
    println!("\n### Summary Statistics\n");
    println!("* **Total unique demos processed**: {}", results.len());
    println!("* **Total size processed**: {:.2} MB", total_size);
    println!("* **Total frames processed**: {}", total_frames);
    println!("* **Total unoptimized time**: {:.3} seconds", total_unopt.as_secs_f64());
    println!("* **Total optimized time**: {:.3} seconds", total_opt.as_secs_f64());
    println!("* **Overall average speedup**: {:.2}x", total_unopt.as_secs_f64() / total_opt.as_secs_f64());
    if mismatch_count > 0 {
        println!("* **WARNING**: {} demo(s) failed the correctness assertion! See log details above.", mismatch_count);
    } else {
        println!("* **Validation**: All parsed states matched perfectly between unoptimized and optimized pipelines!");
    }
}
